@startuml

    left header

        <font color=000 size=18><b>Package:</b> UCD
        
        <font color=000 size=16><b>Ідентифікатор:</b> UC.user.2
        <font color=000 size=16><b>Назва:</b> Доповнення набору даних
        <font color=000 size=16><b>Учасники:</b> користувач, система
        <font color=000 size=16><b>Передумови:</b> користувач має e-mail
        <font color=000 size=16><b>Результат:</b> доповнення набору даних внесеними користувачем
        <font color=000 size=16><b>Виключні ситуації:</b>
        <font color=000 size=16>    <i>EX.user.2.1</i>: користувач вніс дані у минулому
        <font color=000 size=16>    <i>EX.user.2.2</i>: уведені дані не є коректними
        <font color=000 size=16><b>Основний сценарій:</b>

    end header

    |Користувач|

        start;

        :Уводить e-mail адресу для
        ідентифікації;

    |Система|

        :Перевіряє, чи вніс
        користувач дані у минулому;

        note right #f77
        Можлива <b><i>EX.user.2.1</i></b>
        end note

        :Надсилає на введену e-mail
        адресу лист з посиланням на
        сторінку введення даних;
        
    |Користувач|

        :Переходить за посиланням
        на сторінку введення даних;

        :Уводить дані;

    |Система|

        :Перевіряє введені дані на
        коректність;

        note right #f77
        Можлива <b><i>EX.user.2.2</i></b>
        end note

        :Вносить надані користувачем
        дані у базу даних;

        :Зберігає e-mail адресу
        користувача як того,
        який вніс дані;

        :Повідомляє про успішне
        внесення даних;

        stop;

    right footer
        Інформаціна система <b>Bricks</b>
        НТУУ "КПІ" ім. І. Сікорського
        Киів — 2020
    end footer

@enduml