@startuml

    left header

        <font color=000 size=18><b>Package:</b> UCD
        
        <font color=000 size=16><b>Ідентифікатор:</b> UC.user.1
        <font color=000 size=16><b>Назва:</b> Взаємодія з інтерактивною мапою
        <font color=000 size=16><b>Учасники:</b> користувач, система
        <font color=000 size=16><b>Передумови:</b> відсутні
        <font color=000 size=16><b>Результат:</b> інформація згідно із заданими користувачем фільтрами
        <font color=000 size=16><b>Виключні ситуації:</b>
        <font color=000 size=16>    <i>EX.user.1.1</i>: користувач відмовився від уведення балів ЗНО
        <font color=000 size=16><b>Основний сценарій:</b>

    end header

    |Користувач|

    |Система|
 
        start;

        :Пропонує користувачеві
        ввести його бали ЗНО;
        
        note right #f77
        Можлива <b><i>EX.user.1.1</i></b>
        end note
        
    |Користувач|

        :Здійснює пошук бажаного
        ВНЗ/факультету/спеціальності
        на інтерактивній мапі або
        через стрічку пошуку;

    |Система|

        :Відображає коротку інформацію,
        відповідну до знайденого
        користувачем, і надає можливість
        отримати розгорнуту інформацію;

    |Користувач|

        :Переходить на сторінку
        взаємодії з детальною
        інформацією;

        :Взаємодіє з детальною
        інформацією;

        stop;

    right footer
        Інформаціна система <b>Bricks</b>
        НТУУ "КПІ" ім. І. Сікорського
        Киів — 2020
    end footer

@enduml
