@startuml

    left header
        <font color=000 size=18><b>Package:</b> UCD.0
        
        <font color=000 size=16><b>ID:</b> UC.user.1.v1
        <font color=000 size=16><b>Назва:</b> Взаємодія з інтерактивною мапою
        <font color=000 size=16><b>Учасники:</b> користувач, система
        <font color=000 size=16><b>Передумови:</b> відсутні
        <font color=000 size=16><b>Результат:</b> інформація згідно із заданими користувачем фільтрами
        <font color=000 size=16><b>Виключні ситуації:</b>
        <font color=000 size=16>    EX.user.1.1: користувач відмовився від уведення балів ЗНО
        <font color=000 size=16><b>Основний сценарій:</b>

    end header

    |Система|
        start;
        
        : Пропонує користувачеві
        ввести його бали ЗНО;
        
        note right #faa
        Можлива <b>EX.user.1.1</b>
        end note
        
    |Користувач|
        : Здійснює пошук бажаного ВНЗ/факультету/спеціальності
        на інтерактивній мапі або через стрічку пошуку;

    |Система|
        : Пропонує користувачеві
        ввести його бали ЗНО;

    |Користувач|
        : Переходить на сторінку взаємодії
        з детальною інформацією;

        : Взаємодіє з детальною інформацією;

        stop;

    right footer
        Інформаціна система <b>Bricks</b>.
        НТУУ "КПІ" ім. І. Сікорського
        Киів — 2020
    end footer

@enduml
